- title: August 24-25
  url: https://www.eventbrite.com/e/159161415077

- title: September 14-15
  url: https://www.eventbrite.com/e/159162608647

- title: October 26-27
  url: https://www.eventbrite.com/e/159163104129

- title: November 16-17
  url: https://www.eventbrite.com/e/159164285663

- title: December 7-8
  url: https://www.eventbrite.com/e/159164915547


 
 
 
 
 
 
 